---
title: "R Notebook"
output: ioslides_presentation
css: ./styles.css
runtime: shiny
---

# First section

## First slide{#first}

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

## Second slide

Type any R code in the chunk and check the result:

```{r, echo = FALSE}
Ixos <- rnorm(4000, 120, 30)
Primadur <- rnorm(4000, 200, 30)

hist(Ixos, breaks = 30, xlim = c(0, 300), col = rgb(1, 0, 0, 0.5), xlab = "height",
     ylab = "nbr of plants", main = "distribution of height")
hist(Primadur, breaks = 30, xlim = c(0, 300), col = rgb(0, 0, 1, 0.5), add = T)
legend("topright", legend = c("Ixos", "Primadur"), col = c(rgb(1, 0, 0, 0.5),
                                                           rgb(0, 0, 1, 0.5)), pt.cex = 2, pch = 15)
```

# Second section

## Third slide

```{r, echo = FALSE}
ui <- fluidPage(

  titlePanel("Hello!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

    ),

    # Main panel for outputs ----
    mainPanel(
    )
  )
)
# Define server logic  ----
server <- function(input, output) {
}
shinyApp(ui, server)
```